import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'
import fs from 'fs'
import os from 'os'

export default defineConfig(({ mode }) => {
  const isOffice = mode === 'office'

  // For Office add-in, try to use dev certs generated by office-addin-dev-certs
  const getHttpsConfig = () => {
    if (!isOffice) return false

    // Check for office-addin-dev-certs certificates
    const certDir = path.join(os.homedir(), '.office-addin-dev-certs')
    const certPath = path.join(certDir, 'localhost.crt')
    const keyPath = path.join(certDir, 'localhost.key')

    if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
      return {
        key: fs.readFileSync(keyPath),
        cert: fs.readFileSync(certPath),
      }
    }

    // Fallback to basic https (will show certificate warning)
    console.warn('Office add-in dev certs not found. Run: npx office-addin-dev-certs install')
    return true
  }

  return {
    plugins: [react()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
        '@core': path.resolve(__dirname, './src/core'),
        '@platforms': path.resolve(__dirname, './src/platforms'),
      },
    },
    build: {
      outDir: isOffice ? 'dist/office' : 'dist/web',
      rollupOptions: {
        input: isOffice
          ? { taskpane: path.resolve(__dirname, 'taskpane.html') }
          : { main: path.resolve(__dirname, 'index.html') },
      },
    },
    server: {
      port: isOffice ? 3001 : 3000,
      https: getHttpsConfig(),
    },
    preview: {
      port: isOffice ? 3001 : 3000,
      https: getHttpsConfig(),
    },
  }
})
